/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romdz09;

import SevenZip.LzmaAlone;

import java.io.File;
import java.io.FilenameFilter;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFileChooser;




/**
 *
 * @author user
 */
public class find extends javax.swing.JFrame {

    /**
     * Creates new form find
     */
    public NewJFrame fr=null;
    public find() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ftxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();
        ftxt1 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        head5c = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        addr1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        addrd = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        addr2 = new javax.swing.JTextField();
        ji8 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jsize = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        ftxt.setText("5c 00 00 40 00");
        ftxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftxtMouseClicked(evt);
            }
        });

        jButton1.setText("find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt.setColumns(20);
        txt.setRows(5);
        txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txt);

        ftxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftxt1MouseClicked(evt);
            }
        });

        jButton11.setText("in path");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton5.setText("unlzma");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("lzma");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("unlzmaall");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        addr1.setText("0");
        addr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addr1ActionPerformed(evt);
            }
        });

        jButton8.setText("extractall");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        addrd.setText("0");

        jButton9.setText("aaa");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton2.setText("replace");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton10.setText("a.b");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        addr2.setText("0");

        ji8.setText("8");

        jButton3.setText("to f");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jsize.setText("-1");

        jButton4.setText("from f");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton12.setText("aaa2");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("getall rom");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addr1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addrd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jsize, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addr2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ji8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(head5c, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)
                        .addComponent(addr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7)
                        .addComponent(jButton10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ji8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(head5c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ftxt, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxt1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(ftxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //? 0d ? ? ? ? 00 00 40 ? ? ? 00 00 00 00 00 00 00 00 60
        txt.setText("");
        find("");
    }
    boolean test(String[] s2,byte[] fbb,int i){
        if (i>=fr.bb.length-fbb.length) return false;
            for (int i2=0;i2<fbb.length;i2++){
                if (s2[i2].equals("?")) continue;
                if (s2[i2].equals("!0"))
                {
                   if (fr.bb[i+i2]==0) {return false;}
                
                }else
                if (fbb[i2]!=fr.bb[i+i2]) {return false;}
            }
            return true;
    }
    public void unlzma(){
        txt.setText("");ftxt.setText("5c 00 00 40 00");
        find("");
        LzmaAlone.saveaab=false;
        extract(true);ab();
        LzmaAlone.saveaab=true;
        extract(true);ab();
    }
    void find(String fname){
                String ss=ftxt.getText().trim();
                if (ss.equals("")){
                    String s1=ftxt1.getText();
                    if (s1.equals("")) ss="5c 00 00 40 00";
                    else
                    for (int i=0;i<s1.length();i++){
                        ss+=functions.tohex(s1.charAt(i));
                    }
                    ftxt.setText(ss);
                }
        
                int x0=0,x1=0;

                
                String[] s2=ss.split(" ");
                
                
                byte[] fbb=new byte[s2.length];
                
                for (int i=0;i<s2.length;i++){
                    fbb[i]=functions.str2byte(s2[i]);
                }
                for (int i=0;i<s2.length;i++){
                    myLog.Systemoutprintln("=="+i+"="+s2[i]+"=="+fbb[i]+"==");
                }

        for (int i=0;i<fr.bb.length-fbb.length;i++){
            //00 00 00 00 00 00 00 00 60
            boolean da=test(s2,fbb,i);


            if (da)
            {
                boolean da0=test(s2,fbb,x0);
                String nolzma="";
                if (!da0) nolzma="\tnolzma";
                x1=i;
                int dd=x1-x0;
                //dd=fr.bb.length-fbb.length-x0;
                if (x0==0&&!fname.equals("")){
                    if (test(s2,fbb,0)) 
                txt.setText(txt.getText()+functions.tohex(x0)+"\t"+functions.tohex(dd)+"\t"
                        +functions.tohex(x1)+"\t"+fname+nolzma+"\n");
                }else
                txt.setText(txt.getText()+functions.tohex(x0)+"\t"+functions.tohex(dd)+"\t"
                        +functions.tohex(x1)+"\t"+fname+nolzma+"\n");
                //myLog.Systemoutprintln(""+tohex(i)+"=="+tohex(x1-x0));
                x0=x1;
                
            }
        }
        x1=fr.bb.length-fbb.length;
        int dd=x1-x0;
        //int dd=fr.bb.length-fbb.length-x0;
                boolean da0=test(s2,fbb,x0);
                String nolzma="";
                if (!da0) nolzma="nolzma";
        if (x0==0&&!fname.equals("")){
                    if (test(s2,fbb,0)) 
                txt.setText(txt.getText()+functions.tohex(x0)+"\t"+functions.tohex(dd)+"\t"
                        +functions.tohex(x1)+"\t"+fname+nolzma+"\n");
        }else
                txt.setText(txt.getText()+functions.tohex(x0)+"\t"+functions.tohex(dd)+"\t"
                        +functions.tohex(x1)+"\t"+fname+nolzma+"\n");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void addr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addr1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int add1=functions.str2int("#"+addr1.getText().trim());
        int addd=functions.str2int("#"+addrd.getText().trim());
        int add2=functions.str2int("#"+addr2.getText().trim());
        for (int i=0;i<addd;i++){
            fr.bb[add2+i]=fr.bb[add1+i];
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ftxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftxtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtMouseClicked

    private void txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMouseClicked
        // TODO add your handling code here:
        //if (evt.getButton()==java.awt.event.MouseEvent.BUTTON1)

        if ((evt.getModifiers() & java.awt.event.MouseEvent.CTRL_MASK) != 0)
        {
        int pp=txt.getCaretPosition();
        try{
        int pl=txt.getLineOfOffset(pp);

            int p1=txt.getLineStartOffset(pl);
            int p2=txt.getLineEndOffset(pl);
            String ss="";

            if (p1>=0 && p2-p1>=0)
                ss=txt.getText().substring(p1,p2);
            String[] s2=ss.split("\t");
if (s2.length>3&&!s2[3].trim().equals("")){
    fr.setrom000(s2[3].trim());
}
            fr.settable(s2[0]);
            addr1.setText(s2[0]);
            addrd.setText(s2[1]);
            addr2.setText(s2[0]);
            //fr.repaint();
            
            
        }catch(Exception e){
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_txtMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //to
        int add1=functions.str2int("#"+addr1.getText().trim());
        int addd=functions.str2int("#"+addrd.getText().trim());
        int add2=functions.str2int("#"+addr2.getText().trim());
        byte[] tbb=new byte[addd];
        for (int i=0;i<addd;i++){
            tbb[i]=fr.bb[add1+i];
        }
        functions.byte2file(fr.getpath()+"tmp",tbb);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //from
        int add1=functions.str2int("#"+addr1.getText().trim());
        int addd=functions.str2int("#"+addrd.getText().trim());
        int add2=functions.str2int("#"+addr2.getText().trim());
        byte[] tbb=functions.file2byte(fr.getpath()+"tmp");
        for (int i=0;i<tbb.length;i++){
            fr.bb[add2+i]=tbb[i];
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String ss="d \""+fr.getpath()+"tmp\" \""+fr.getpath()+"tmp2\"";

            LzmaAlone.exec(ss);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //e -lc2 -d22 /home/user/Desktop/1/_00/dop/15/1/tmp1111 /home/user/Desktop/1/_00/dop/15/1/tmp11112
                String ss="e -lc2 -d22 \""+fr.getpath()+"tmp2\" \""+fr.getpath()+"tmp\"";

            LzmaAlone.exec(ss);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        LzmaAlone.saveaab=false;
        extract(true);ab();
        LzmaAlone.saveaab=true;
        extract(true);ab();
    }
    public void extract(boolean lzma){

        int i8=functions.str2int(ji8.getText());       
        int size=functions.str2int(jsize.getText());
        LzmaAlone.head5c=head5c.getText();
         LzmaAlone.i8=i8;
         LzmaAlone.size=size;
         
        File f=new File(fr.getpath());
        File[] f2=f.listFiles(new FilenameFilter() {

            @Override
            public boolean accept(File dir, String name) {
                return name.endsWith(".b")||name.endsWith(".a");
            }
        });
        
        for (File ff:f2) ff.delete();
        

        String[] txt2=txt.getText().split("\n");
        for (int i=0;i<txt2.length;i++)
        {String[] s2=txt2[i].split("\t");
        try{

            




            
            

        int add1=functions.str2int("#"+s2[0].trim());
        int addd=functions.str2int("#"+s2[1].trim());


        functions.byte2file(fr.getpath()+s2[0].trim()+".a",fr.bb,add1,addd);
        if (lzma){
            if (txt2[i].contains("nolzma")){
                functions.byte2file(fr.getpath()+s2[0].trim()+"a.b",fr.bb,add1,addd);
            }else
            {

            String ss="d \""+fr.getpath()+s2[0].trim()+".a\" \""+fr.getpath()+s2[0].trim()+".b\"";

                LzmaAlone.exec(ss);
    //            if (LzmaAlone.nn>=0)
      //          myLog.Systemoutprintln("=====================================place=============================================="
        //                +LzmaAlone.nn);

            }
        }
        }catch(Exception e){
            myLog.Systemoutprintln("error======="+e.toString());

        }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        extract(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        

        
        
        String ss=functions.file2str(fr.getpath()+"1/FontData.c");
        System.out.println("11=="+ss+"==");
        int p1=ss.indexOf("{");
        int p2=ss.indexOf("}",p1);
        ss=ss.substring(p1+1, p2).replace("\n", "");//5c 00 00 40 00 c6 0d 00 00 00 00 00 00 00 00 
       // ss=ss.replace("0x5D,0x0,0x0,0x1,0x0,0x0,",ftxt.getText());//
                //"0x5D,0x0,0x0,0x1,0x0,0x6,0x0d,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00");
        String[] s2=ss.split(",");
        byte[] bt=new byte[s2.length];
        for (int i=0;i<s2.length;i++){
            bt[i]=(byte)functions.str2int(s2[i]);
            if (i<33)System.out.println(s2[i]+"="+(bt[i]&0xFF)+"="+functions.tohex(bt[i]&0xFF));
        }
        functions.byte2file(fr.getpath()+"1/font.lzma", bt);
        
        
        
        
                int kk=functions.str2int(addr2.getText());
        ss="d \""+fr.getpath()+"1/font.lzma\" \""+fr.getpath()+"1/tt22.b\"";
        int i8=functions.str2int(ji8.getText());       
        int size=functions.str2int(jsize.getText());
        
        LzmaAlone.head5c=head5c.getText();
         LzmaAlone.i8=i8;
         LzmaAlone.size=size;
            LzmaAlone.exec(ss);                
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
//        correcttxt();
//        if (1==1) return;
        
        
        String ff=fr.getpath();

        final JFileChooser fc = new JFileChooser();

        fc.setCurrentDirectory(new File(ff));
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            myLog.Systemoutprintln("Opening: " + file.getName());
            ff=file.getParent()+System.getProperty("file.separator");
            
            
            String ss="";
            byte[] bb2=functions.file2byte(file.getPath());
            
            for (int i=0;i<fr.bb.length-257;i++){
                if (i%10000==0) System.out.println(""+(100*i/fr.bb.length));
                if (fr.bb[i]==fr.bb[i+1]) continue;
                int j0=0;
                if (i>500000) j0=i-500000;
                for (int j=j0;j<bb2.length-257;j++){
                    if (j>i+500000) break;
                    boolean da=true; 
                    for (int k=0;k<256;k++){
                        if (fr.bb[i+k]!=bb2[j+k]) {da=false;break;}
                    }
                    if (da){
                        int p=255;
                        for (int k=256;i+k<fr.bb.length&&j+k<bb2.length;k++){
                            if (fr.bb[i+k]!=bb2[j+k]) break;
                            else p=k;
                        }
                        
                        System.out.println(""+functions.tohex(i)+"\t"+p+"\t"+functions.tohex(i+p)+"\t\t"
                                +functions.tohex(j)+"\t"+functions.tohex(j+p));
                        ss+=functions.tohex(i)+"\t"+p+"\t"+functions.tohex(i+p)+"\t\t"
                                +functions.tohex(j)+"\t"+functions.tohex(j+p)+"\n";
                        i+=p;
                        if (i>=fr.bb.length-257) {break;}
                    }
                }
            }
            ss+="\n"+functions.tohex(fr.bb.length)+"\t\t\t\t"
                                +functions.tohex(bb2.length)+"\n";
            txt.setText(ss);

        } else {
            myLog.Systemoutprintln("cancel: ");
        }        

    }
    public void ab(){
                String[] txt2=txt.getText().split("\n");
                String ss="";
        for (int i=0;i<txt2.length;i++)
        {String[] s2=txt2[i].split("\t");
        try{

            File f=new File(fr.getpath()+s2[0].trim()+".b");
            boolean da=false;
            if (f.exists()) {
                if (f.length()<10) {txt2[i]+="\tnolzma";
                    f.delete();
                    da=true;
                }
            }
//            if (i==txt2.length-1||da){
  //             File fa=new File(fr.getpath()+s2[0].trim()+".a");
    //           File fab=new File(fr.getpath()+s2[0].trim()+"a.b");
      //         Files.copy(fa.toPath(),fab.toPath());
        //    }

        }catch(Exception e){
            myLog.Systemoutprintln("error======="+e.toString());
            
        }
        ss+=txt2[i]+"\n";
        }
        
        txt.setText(ss);
    }//GEN-LAST:event_jButton10ActionPerformed
/*    public void correcttxt(){
         String[] txt2=txt.getText().split("\n");
         String ss="";

         for (int i=0;i<txt2.length;i++){
             //String[] s2=txt2[i].split("\t");
             if (i==0) {ss+=txt2[i]+"\n";continue;}
             if (!(txt2[i].contains("nolzma")&&txt2[i-1].contains("nolzma"))){
                 ss+=txt2[i]+"\n";
             }
         }
         txt.setText(ss);
    }*/
    private void ftxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftxt1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxt1MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        txt.setText("");
        File ff = new File(fr.getpath());// + "/_ROM.extracted");
        File[] f2 = ff.listFiles();
        Arrays.sort(f2);
        int n = 0;
        for (int i = 0; i < f2.length; i++) {
            if (((f2[i].getName().endsWith(".b") && f2[i].isFile())
                    || (f2[i].getName().endsWith(".a") && f2[i].isFile())
                    || (f2[i].getName().endsWith(".bin") && f2[i].isFile())
                    || (!f2[i].getName().contains(".") && f2[i].isFile())) && (!f2[i].getName().toLowerCase().contains("boot"))) {
                fr.setrom000(f2[i].getName());
                find(f2[i].getName());
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String ss0=functions.file2str(fr.getpath()+"1/MTKPropFont.h");
        
        String[] ss2=ss0.split("const");
        for (int i1=0;i1<ss2.length;i1++){
            
            String st=ss2[i1];
            if (st.startsWith("/*")) continue;
            String nam=st.split("\n")[0].replace("=", "").replace("{", "").replace(" ", "");
            System.out.println("========="+nam);

        String ss=st;
        System.out.println("11=="+ss+"==");
        int p1=ss.indexOf("{");
        int p2=ss.indexOf("}",p1);
        ss=ss.substring(p1+1, p2).replace("\n", "");//5c 00 00 40 00 c6 0d 00 00 00 00 00 00 00 00 
       // ss=ss.replace("0x5D,0x0,0x0,0x1,0x0,0x0,",ftxt.getText());//
                //"0x5D,0x0,0x0,0x1,0x0,0x6,0x0d,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00");
        String[] s2=ss.split(",");
        byte[] bt=new byte[s2.length];
        for (int i=0;i<s2.length;i++){
            bt[i]=(byte)functions.str2int(s2[i]);
            if (i<33)System.out.println(s2[i]+"="+(bt[i]&0xFF)+"="+functions.tohex(bt[i]&0xFF));
        }
        functions.byte2file(fr.getpath()+"1/"+nam, bt);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
                String ff=fr.getpath();

        final JFileChooser fc = new JFileChooser();

        fc.setCurrentDirectory(new File(ff));
        
           // fc.setDialogTitle(choosertitle);
    fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    //
    // disable the "All files" option.
    //
    fc.setAcceptAllFileFilterUsed(false);
        
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            

        ArrayList<File> files=listf(fc.getSelectedFile().getPath());
        String ss="";byte[] bbt;
        for (File f2:files){
            System.out.println("====="+f2.getPath());
            bbt=functions.file2byte(f2.getPath());
            
            
                    
        
        for (int i=0xc0;i<0x100;i++){
            if (bbt[i]==0) break;
            ss+=(char) (bbt[i] & 0xFF);
        }
        ss+="\t";
        for (int i=0x40;i<0xc0;i++){
            if (bbt[i]==0) break;
            ss+=(char) (bbt[i] & 0xFF);
        }
        ss+="\t"+f2.getPath()+"\n";
            
            
        }
        bbt=null;
        txt.setText(ss);
        }
    }//GEN-LAST:event_jButton13ActionPerformed
public ArrayList<File> listf(String directoryName ){
    ArrayList<File> files=new ArrayList<File>();
    listf( directoryName,  files);
    return files;
}
    public void listf(String directoryName, ArrayList<File> files) {
        File directory = new File(directoryName);

        // get all the files from a directory
        File[] fList = directory.listFiles();
        for (File file : fList) {
            if (file.isFile()) {
                String fss=file.getName().toLowerCase();
                if (fss.equals("rom")||fss.equals("file_01_mtk"))
                files.add(file);
            } else if (file.isDirectory()) {
                listf(file.getAbsolutePath(), files);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(find.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new find().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addr1;
    private javax.swing.JTextField addr2;
    private javax.swing.JTextField addrd;
    private javax.swing.JTextField ftxt;
    private javax.swing.JTextField ftxt1;
    private javax.swing.JTextField head5c;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ji8;
    private javax.swing.JTextField jsize;
    private javax.swing.JTextArea txt;
    // End of variables declaration//GEN-END:variables
}
