/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romdz09;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {

    public class cellString {
        String ss;
        public boolean select=false;
        public cellString(String _ss){
            ss=_ss;
        }
        public String toString(){
            return ss;
        }
    }
    public class StatusColumnCellRenderer extends DefaultTableCellRenderer {
  @Override
  public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int col) {

    //Cells are by default rendered as a JLabel.
    JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);

    //Get the status for the current row.


    if (value==null) l.setBackground(Color.white);
    else if (cellString.class.isInstance(value) && ((cellString)value).select)
      l.setBackground(Color.ORANGE);
    else{
       if (isSelected)
           l.setBackground(Color.blue);
       else
l.setBackground(Color.white);
    }
  //Return the JLabel which renders the cell.
    
    //l.setBackground(Color.white);
  return l;

}
    }
    
    /**
     * Creates new form NewJFrame
     */
    int nn=16;
    int hh=0;
    void setadvance(boolean adv){
        jpanadv.setVisible(adv);
        if (adv){myLog.Systemoutprintln(""+jpanadv.getHeight());
            //int yy=jpan.getHeight()+this.getInsets().top+jpanadv.getHeight();
            int xx=this.getWidth();
            this.setSize(xx,hh);            
        }else{
            int yy=jpan.getHeight()+this.getInsets().top;//this.getHeight()-jpanadv.getHeight();
            int xx=this.getWidth();
            this.setSize(xx,yy);
        }
    }
    help hlp;
    Timer tim;
    public NewJFrame() {
        initComponents();
        
            tim = new Timer(200, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (jButton7.getModel().isPressed()){
                    gotodel();
                }else
                if (jButton8.getModel().isPressed()){
                    gotodel();
                }else
                if (jButton9.getModel().isPressed()){
                    gotodel();
                }else {
                    tim.stop();
                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });

        if (fr1==null) fr1=new ris1();
        fr1.fr=this;
        if (hlp==null) hlp=new help();

        setlang(0);
        
        hh=this.getHeight();

        newtab();
        String fft=System.getProperty("user.dir");
        
        
        setadvance(false);
        myLog.isdebug=false;
        
        myLog.Systemoutprintln("==="+fft);
        
        if (!(fft.toLowerCase().contains("netbeans")
              ||  fft.toLowerCase().contains("javaprojects")
                )) jpath.setText(fft);
        else{
            setadvance(true);this.jadvance.setSelected(true);
            myLog.isdebug=true;            
        }
    }
    void newtab(){
           String[] s2=new String[nn+2];
        for (int i=1;i<nn+1;i++) s2[i]=""+(i-1);
        s2[0]="#";
        s2[nn+1]="abcdef";
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            s2
        ));
        int h=tab.getColumnModel().getColumn(nn+1).getPreferredWidth();
        tab.getColumnModel().getColumn(0).setPreferredWidth(h*2);
        tab.getColumnModel().getColumn(nn+1).setPreferredWidth(h*5);
        
        for (int i=1;i<tab.getColumnCount()-1;i++){
            tab.getColumnModel().getColumn(i).setCellRenderer(new StatusColumnCellRenderer());
            if (j101.getState())
                tab.getColumnModel().getColumn(i).setPreferredWidth(h*2);
            else
                tab.getColumnModel().getColumn(i).setPreferredWidth(h);  
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpan = new javax.swing.JPanel();
        jnew = new javax.swing.JButton();
        jpath = new javax.swing.JTextField();
        jrom000 = new javax.swing.JTextField();
        jgetpic = new javax.swing.JButton();
        jrom = new javax.swing.JTextField();
        jsave = new javax.swing.JButton();
        jextract = new javax.swing.JButton();
        jinfo = new javax.swing.JButton();
        jload = new javax.swing.JButton();
        jlang = new javax.swing.JComboBox();
        jsave1 = new javax.swing.JButton();
        jadvance = new javax.swing.JCheckBox();
        jpanadv = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jnn = new javax.swing.JSpinner();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        cc = new javax.swing.JTextField();
        ddd = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        ddd1 = new javax.swing.JTextField();
        jfind = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jda0 = new java.awt.Checkbox();
        jddd2 = new javax.swing.JLabel();
        j101 = new java.awt.Checkbox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("v.1.01 mail:sarchilg@gmail.com");

        jnew.setText("...");
        jnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnewActionPerformed(evt);
            }
        });

        jpath.setText("/home/user/Desktop/1/_00/dop/15 15/");
        jpath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpathActionPerformed(evt);
            }
        });

        jrom000.setText("ROM000");
        jrom000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrom000ActionPerformed(evt);
            }
        });

        jgetpic.setText("get pictures");
        jgetpic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgetpicActionPerformed(evt);
            }
        });

        jrom.setText("ROM");
        jrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jromActionPerformed(evt);
            }
        });

        jsave.setText("save");
        jsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaveActionPerformed(evt);
            }
        });

        jextract.setText("extract");
        jextract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jextractActionPerformed(evt);
            }
        });

        jinfo.setText("info");
        jinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jinfoActionPerformed(evt);
            }
        });

        jload.setText("load");
        jload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloadActionPerformed(evt);
            }
        });

        jlang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Russian" }));
        jlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlangActionPerformed(evt);
            }
        });

        jsave1.setText("help");
        jsave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsave1ActionPerformed(evt);
            }
        });

        jadvance.setToolTipText("advance");
        jadvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadvanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanLayout = new javax.swing.GroupLayout(jpan);
        jpan.setLayout(jpanLayout);
        jpanLayout.setHorizontalGroup(
            jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanLayout.createSequentialGroup()
                .addGroup(jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpanLayout.createSequentialGroup()
                        .addComponent(jnew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpath, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanLayout.createSequentialGroup()
                        .addComponent(jload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jinfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jgetpic)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanLayout.createSequentialGroup()
                        .addComponent(jrom000, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jsave))
                    .addGroup(jpanLayout.createSequentialGroup()
                        .addComponent(jextract)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jadvance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsave1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrom, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jpanLayout.setVerticalGroup(
            jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanLayout.createSequentialGroup()
                .addGroup(jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jsave)
                        .addComponent(jrom000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jnew, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jinfo)
                    .addComponent(jgetpic)
                    .addComponent(jextract)
                    .addComponent(jload)
                    .addComponent(jlang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsave1)
                    .addComponent(jadvance))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jButton5.setText("from table");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jnn.setModel(new javax.swing.SpinnerNumberModel());
        jnn.setName(""); // NOI18N
        jnn.setValue(16);

        jButton6.setText("find");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("/\\");
            jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    jButton7MousePressed(evt);
                }
            });
            jButton7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton7ActionPerformed(evt);
                }
            });

            jButton8.setText("\\/");
            jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    jButton8MousePressed(evt);
                }
            });
            jButton8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton8ActionPerformed(evt);
                }
            });

            cc.setText("0");
            cc.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ccActionPerformed(evt);
                }
            });

            ddd.setText("0");
            ddd.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    dddActionPerformed(evt);
                }
            });

            jButton2.setText("get");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jButton3.setText("replace");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });

            jButton10.setText("lzma");
            jButton10.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton10ActionPerformed(evt);
                }
            });

            ddd1.setText("0");
            ddd1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ddd1ActionPerformed(evt);
                }
            });

            jfind.setText("00");
            jfind.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jfindActionPerformed(evt);
                }
            });

            tab.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            tab.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
                public void propertyChange(java.beans.PropertyChangeEvent evt) {
                    tabPropertyChange(evt);
                }
            });
            jScrollPane1.setViewportView(tab);

            jButton9.setText("\\/");
            jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    jButton9MousePressed(evt);
                }
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton9MouseClicked(evt);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    jButton9MouseEntered(evt);
                }
            });
            jButton9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton9ActionPerformed(evt);
                }
            });

            jda0.setLabel("0");

            jddd2.setText("-");

            j101.setLabel("101");

            javax.swing.GroupLayout jpanadvLayout = new javax.swing.GroupLayout(jpanadv);
            jpanadv.setLayout(jpanadvLayout);
            jpanadvLayout.setHorizontalGroup(
                jpanadvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanadvLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(jpanadvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jpanadvLayout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jpanadvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ddd, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addComponent(jddd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jfind, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpanadvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpanadvLayout.createSequentialGroup()
                            .addComponent(jButton7)
                            .addGap(18, 18, 18)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ddd1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpanadvLayout.createSequentialGroup()
                            .addComponent(jButton8)
                            .addGap(18, 18, 18)
                            .addComponent(jButton5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jda0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                    .addGroup(jpanadvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanadvLayout.createSequentialGroup()
                            .addComponent(j101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jnn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            );
            jpanadvLayout.setVerticalGroup(
                jpanadvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanadvLayout.createSequentialGroup()
                    .addGroup(jpanadvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpanadvLayout.createSequentialGroup()
                            .addGroup(jpanadvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton7)
                                .addComponent(ddd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jpanadvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton8)
                                .addComponent(jddd2)))
                        .addGroup(jpanadvLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jpanadvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpanadvLayout.createSequentialGroup()
                                    .addGroup(jpanadvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2)
                                        .addComponent(jButton3)
                                        .addComponent(ddd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton6)
                                        .addComponent(jButton9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jpanadvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jpanadvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jnn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton5)
                                            .addComponent(jButton10))
                                        .addComponent(jda0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(j101, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpanadv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpanadv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    //int ii=0
    byte[] bb=null;
    private void jloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloadActionPerformed
        // TODO add your handling code here:
        readtable();

    }
    public void readtable()
    {
        this.setTitle(jpath.getText()+jrom000.getText());
        bb=null;
        functions.getmemoryinfo();
        bb=functions.file2byte(jpath.getText()+jrom000.getText());

        int dd=functions.str2int("#"+ddd.getText().trim());
        settable(dd);
    }//GEN-LAST:event_jloadActionPerformed
    public void inittable(){
        newtab();
        DefaultTableModel model = (DefaultTableModel) tab.getModel();
        
        String[] s2=new String[nn+1];
        
        for (int ii=0;ii<100;ii++){
         //   for (int i=0;i<nn;i++) s2[i+1]=String.format("%02X ", bb[ii*nn+i]);
         //   s2[0]=String.format("%02X ",ii*nn);
            model.addRow(s2);
        }        
    }
    private void dddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dddActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int dd=functions.str2int("#"+ddd.getText().trim());
        settable(dd);
    }
    public void settable(String ss){
        ddd.setText(ss);
        int dd=functions.str2int("#"+ddd.getText().trim());
        settable(dd);        
    }
    public void readtable(String ss,String srom)
    {
        jrom000.setText(srom);
        ddd.setText(ss);
        readtable();        
    }
    
    String byte2table(byte bb,int typ){
        if (typ==16)
            return String.format("%02X ", bb);
        String ss="";
         for (byte k = 0; k < 8; k++) {
                ss += "" + functions.getbit(bb, k);
            }
         return ss;
    }
    String byte2tableh(byte bb,int typ){
        if (typ==16){
            char c = (char) (bb & 0xFF);
            if (c<32) c=' ';
            return ""+c;
        }
        return String.format("%02X ", bb);
    }    
    void settable(int dd)
    {   int i101=16;
        if (j101.getState()) i101=1;
        if (bb==null) {readtable();return;}
        nn=(Integer)jnn.getValue();
        inittable();
        String[] s2=jfind.getText().split(" ");
        Byte[] b2=new Byte[s2.length];
        for (int i=0;i<s2.length;i++){
            if (s2[i].contains("?"))
                b2[i]=null;
            else
                b2[i]=functions.str2byte(s2[i]);
        }
        int k=0;
        for (int ii=0;ii<100;ii++){
            String ss="";
            for (int i=0;i<nn;i++){ 
                //myLog.Systemoutprintln(""+ii+"="+i);
                if (ii*nn+i+dd<bb.length){
                    cellString cs=new cellString(byte2table(bb[ii*nn+i+dd],i101));
                    boolean da=true;
                    for (int i5=0;i5<s2.length;i5++){
                        if (b2[i5]==null) continue;
                        if (bb[ii*nn+i+dd+i5]!=b2[i5]){
                            da=false;break;
                        }
                    }
                    if (da) k=b2.length;
                    if (k>0) {cs.select=true;k--;}
                    tab.getModel().setValueAt(cs, ii, i+1);
                    ss+=byte2tableh(bb[ii*nn+i+dd],i101);
                }
            }
            tab.getModel().setValueAt(ss, ii, nn+1);
            tab.getModel().setValueAt(String.format("%02X ", ii*nn+dd), ii, 0);
        }
        int dd1=dd % 16;
        for (int i=1;i<tab.getColumnCount()-1;i++)
        tab.getColumnModel().getColumn(i).setHeaderValue(functions.hex2str((i-1+dd1) % 16));
        tab.getTableHeader().repaint();
        jddd2.setText(""+dd);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int dd=functions.str2int("#"+ddd.getText().trim());
        
        String[] s2=cc.getText().trim().split(" ");
        byte[] b2=new byte[s2.length];
        for (int i=0;i<b2.length;i++) b2[i]=functions.str2byte(s2[i]);
        
        //int cc6=functions.str2int(cc.getText().trim());
        
        int dd1=functions.str2int("#"+ddd1.getText().trim());
        if (dd1==0){
            int k=0;
            int[] i2=tab.getSelectedRows();
            for (int i=0;i<i2.length;i++){
                for (int j=0;j<tab.getColumnCount()-2;j++){
                    String ss=tab.getModel().getValueAt(i2[i],j+1).toString().trim();
                    int kk=i%b2.length;
                    k++;
                    
                  if (!(jda0.getState()&&ss.equals("00"))) { 
                    cellString cs=new cellString(String.format("%02X ", b2[kk]));
                    tab.getModel().setValueAt(cs, i2[i],j+1);
                  }
                }
            }
        }else
        for (int i=0;i<dd1;i++) {
            int j=i%b2.length;
            if (!(jda0.getState()&&bb[i+dd]==0))
            bb[i+dd]=b2[j];
/*            if (cc6==1000){
                bb[i+dd]=(byte)(~bb[i+dd]);
            }else{
            if (bb[i+dd]!=0)
            bb[i+dd]=cc5;
            }*/
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    public String getpath(){
        return jpath.getText();
    }
    public void setrom000(String ff){
        jrom000.setText(ff);
        readtable();
    }
    private void jsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaveActionPerformed
        // TODO add your handling code here:
        functions.byte2file(jpath.getText()+jrom.getText(),bb);
    }//GEN-LAST:event_jsaveActionPerformed

    private void ddd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddd1ActionPerformed

    private void jpathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpathActionPerformed

    private void tabPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tabPropertyChange

    byte tab2byte(String s,int typ){
if (typ==16){
                
                if (s.length()==2){
                return (byte) ((Character.digit(s.charAt(0), 16) << 4)
                             + Character.digit(s.charAt(1), 16));

                }
                else if (s.length()==1){
                 return (byte) (Character.digit(s.charAt(0), 16));                   

                }
}
    int b=0;
    for (int i=0;i<s.length();i++) {
        if (s.charAt(s.length()-i-1)=='1') b=b*2+1;
        else b=b*2;
    }
return (byte) b;
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
int dd=functions.str2int("#"+ddd.getText().trim());
int i101=16;
if (j101.getState()) i101=1;
        for (int ii=0;ii<100;ii++){
            for (int i=0;i<nn;i++){ 
                //myLog.Systemoutprintln(""+ii+"="+i);
                String s=tab.getModel().getValueAt(ii, i+1).toString().trim();
                

                    bb[ii*nn+i+dd]=  tab2byte(s,i101);

                
//                byte b=Byte.decode("#"+tab.getModel().getValueAt(ii, i+1).toString().trim());

              //bb[ii*nn+i+dd]=  b;
                //tab.getModel().setValueAt(String.format("%02X ", bb[ii*nn+i+dd]), ii, i+1);

            }
//            tab.getModel().setValueAt(String.format("%02X ", ii*nn+dd), ii, 0);
        }        
    }//GEN-LAST:event_jButton5ActionPerformed

    find fr=null;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (fr==null) fr=new find();
        fr.setVisible(true);
        fr.fr=this;
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void ccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccActionPerformed
    ris1 fr1=null;
    private void jgetpicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgetpicActionPerformed
        // TODO add your handling code here:

        if (fr1==null) fr1=new ris1();
        else if (!fr1.isVisible()){
            fr1.dispose();
            fr1=new ris1();
        }
        fr1.fr=this;
        fr1.setadvance(jpanadv.isVisible());
        fr1.updatefills();
        fr1.setVisible(true);
    }//GEN-LAST:event_jgetpicActionPerformed

    private void jrom000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrom000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrom000ActionPerformed

    private void jromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jromActionPerformed
    lzma frlzma=null;
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if (frlzma==null) frlzma=new lzma();
        frlzma.fr=this;
        frlzma.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfindActionPerformed

    private void jnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnewActionPerformed
        // TODO add your handling code here:

        String ff=jpath.getText();

        final JFileChooser fc = new JFileChooser();

        fc.setCurrentDirectory(new File(ff));
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            myLog.Systemoutprintln("Opening: " + file.getName());
            ff=file.getParent()+System.getProperty("file.separator");
            jpath.setText(ff);
            jrom000.setText(file.getName());
            //jrom.setText(file.getName().replace("000", ""));
            readtable();
            fr1.dispose();fr1=null;
             fr1=new ris1();
        } else {
            myLog.Systemoutprintln("cancel: ");
        }
    }//GEN-LAST:event_jnewActionPerformed

    private void jinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jinfoActionPerformed
        // TODO add your handling code here:
        hlp.setVisible(true);

        String ss="";
        
        for (int i=0xc0;i<0x100;i++){
            if (bb[i]==0) break;
            ss+=(char) (bb[i] & 0xFF);
        }
        ss+="\t";
        for (int i=0x40;i<0xc0;i++){
            if (bb[i]==0) break;
            ss+=(char) (bb[i] & 0xFF);
        }
        ss+="\t"+jpath.getText()+jrom000.getText();
        myLog.Systemoutprintln(ss);
        hlp.setText(ss);
    }//GEN-LAST:event_jinfoActionPerformed

    private void jextractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jextractActionPerformed
        // TODO add your handling code here:
        if (fr==null) fr=new find();
        
        fr.fr=this;
        this.readtable();
        fr.unlzma();
    }//GEN-LAST:event_jextractActionPerformed

    private void jlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlangActionPerformed
        // TODO add your handling code here:
        setlang(jlang.getSelectedIndex());
    }//GEN-LAST:event_jlangActionPerformed

    private void jsave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsave1ActionPerformed
        // TODO add your handling code here:
        hlp.setVisible(true);
        hlp.sethelp(jlang.getSelectedIndex());
    }//GEN-LAST:event_jsave1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

    }
    void gotodel(){
        int dd=functions.str2int("#"+ddd.getText().trim());
        //myLog.Systemoutprintln(""+dd);
        dd+=kdel*nn;
        if (dd<0) dd=0;
        if (dd>bb.length) dd=(bb.length/nn+1)*nn-100*nn;
        ddd.setText(functions.tohex(dd));
        settable(dd);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MousePressed
        // TODO add your handling code here:
        kdel=-1;
        gotodel();
        tim.start();
    }//GEN-LAST:event_jButton9MousePressed
    int kdel=0;
    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        // TODO add your handling code here:
        kdel=10;
        gotodel();
        tim.start(); 
    }//GEN-LAST:event_jButton7MousePressed

    private void jButton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MousePressed
        // TODO add your handling code here:
        kdel=-10;
        gotodel();
        tim.start(); 
    }//GEN-LAST:event_jButton8MousePressed

    private void jadvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadvanceActionPerformed
        // TODO add your handling code here:
        this.setadvance(this.jadvance.isSelected());
    }//GEN-LAST:event_jadvanceActionPerformed

    void setlang(int ii){
        if (ii==0){//en
            jnew.setText("new");jnew.setToolTipText("set path to new rom");
            jinfo.setText("info");jinfo.setToolTipText("get rom info");
            jsave.setText("save");jsave.setToolTipText("save rom");
            jload.setText("load");jload.setToolTipText("load rom");
            jgetpic.setText("get pictures");jgetpic.setToolTipText("get pictures and other resources");
            jextract.setText("extract");jextract.setToolTipText("extract rom parts to files with extention .a and decompile to files with extention .b");
            jrom.setToolTipText("rom to save");
            jrom000.setToolTipText("source rom");
            jpath.setToolTipText("path to rom");
        }else{//ru
            jnew.setText("новый");jnew.setToolTipText("задать путь к новому rom");
            jinfo.setText("инфо");jinfo.setToolTipText("получить информацию о rom");
            jsave.setText("записать");jsave.setToolTipText("записать rom");
            jload.setText("загрузить");jload.setToolTipText("загрузить rom");
            jgetpic.setText("получить рисунки");jgetpic.setToolTipText("получить рисунки и другие ресурсы");
            jextract.setText("извлечь");jextract.setToolTipText("извлечь части rom в файлы с расширение .a  и декомпиляция в файлы с расширением .b");
            jrom.setToolTipText("rom для записи");
            jrom000.setToolTipText("исходный rom");
            jpath.setToolTipText("путь к rom");            
        }
        fr1.setlang(ii);
        fr1.frtxt1.setlang(ii);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cc;
    private javax.swing.JTextField ddd;
    private javax.swing.JTextField ddd1;
    private java.awt.Checkbox j101;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jadvance;
    private java.awt.Checkbox jda0;
    private javax.swing.JLabel jddd2;
    private javax.swing.JButton jextract;
    private javax.swing.JTextField jfind;
    private javax.swing.JButton jgetpic;
    private javax.swing.JButton jinfo;
    private javax.swing.JComboBox jlang;
    private javax.swing.JButton jload;
    private javax.swing.JButton jnew;
    private javax.swing.JSpinner jnn;
    private javax.swing.JPanel jpan;
    private javax.swing.JPanel jpanadv;
    private javax.swing.JTextField jpath;
    private javax.swing.JTextField jrom;
    private javax.swing.JTextField jrom000;
    private javax.swing.JButton jsave;
    private javax.swing.JButton jsave1;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
